development:
  adapter: postgresql
  encoding: utf8
  database: calendar
  username: postgres
  password: 000000
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: calendar
  username: postgres
  password: 000000
  host: localhost